name: Run clang-format Linter

on:
  push:
  pull_request:
    types: [assigned, opened, edited, reopened, synchronize, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: '.'
        exclude: './third_party ./external'
        extensions: 'cs'
        clangFormatVersion: 12
        style: google